-- B2B Procurement - Product Catalog Core Schema v1.0.0

CREATE TABLE b2b_categories (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    parent_id BIGINT UNSIGNED DEFAULT NULL,
    name_fa VARCHAR(150) NOT NULL,
    name_en VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    description TEXT DEFAULT NULL,
    icon VARCHAR(50) DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    sort_order INT UNSIGNED DEFAULT 0,
    status TINYINT(1) DEFAULT 1,
    depth SMALLINT UNSIGNED DEFAULT 0,
    path VARCHAR(500) DEFAULT '',
    product_count INT UNSIGNED DEFAULT 0,
    deleted_at DATETIME DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cat_slug (slug),
    KEY idx_cat_parent (parent_id),
    KEY idx_cat_status (status),
    KEY idx_cat_sort (sort_order),
    KEY idx_cat_depth (depth),
    KEY idx_cat_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE b2b_products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    sku VARCHAR(100) NOT NULL,
    name_fa VARCHAR(255) NOT NULL,
    name_en VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description LONGTEXT DEFAULT NULL,
    short_desc VARCHAR(500) DEFAULT NULL,
    category_id BIGINT UNSIGNED DEFAULT NULL,
    base_unit VARCHAR(20) DEFAULT 'pcs',
    weight DECIMAL(10,3) DEFAULT NULL,
    weight_unit VARCHAR(10) DEFAULT 'kg',
    min_order_qty DECIMAL(10,3) DEFAULT 1.000,
    max_order_qty DECIMAL(10,3) DEFAULT NULL,
    lead_time_days SMALLINT UNSIGNED DEFAULT 0,
    status TINYINT(1) DEFAULT 0,
    visibility TINYINT(1) DEFAULT 1,
    has_variants TINYINT(1) DEFAULT 0,
    has_attributes TINYINT(1) DEFAULT 0,
    meta JSON DEFAULT NULL,
    tags JSON DEFAULT NULL,
    images JSON DEFAULT NULL,
    deleted_at DATETIME DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_prod_sku (sku),
    UNIQUE KEY uk_prod_slug (slug),
    KEY idx_prod_category (category_id),
    KEY idx_prod_status (status),
    KEY idx_prod_visibility (visibility),
    KEY idx_prod_created (created_at),
    KEY idx_prod_deleted (deleted_at),
    FULLTEXT KEY ft_prod_search (name_fa, name_en, sku, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE b2b_product_attributes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name_fa VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL,
    type VARCHAR(30) NOT NULL DEFAULT 'text',
    options JSON DEFAULT NULL,
    is_required TINYINT(1) DEFAULT 0,
    is_filterable TINYINT(1) DEFAULT 0,
    is_searchable TINYINT(1) DEFAULT 0,
    sort_order INT UNSIGNED DEFAULT 0,
    status TINYINT(1) DEFAULT 1,
    deleted_at DATETIME DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_attr_code (code),
    KEY idx_attr_type (type),
    KEY idx_attr_status (status),
    KEY idx_attr_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE b2b_attribute_values (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    product_id BIGINT UNSIGNED NOT NULL,
    attribute_id BIGINT UNSIGNED NOT NULL,
    value_text TEXT DEFAULT NULL,
    value_number DECIMAL(12,3) DEFAULT NULL,
    sort_order INT UNSIGNED DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_av_product (product_id),
    KEY idx_av_attribute (attribute_id),
    KEY idx_av_product_attr (product_id, attribute_id),
    CONSTRAINT fk_av_product FOREIGN KEY (product_id) REFERENCES b2b_products(id) ON DELETE CASCADE,
    CONSTRAINT fk_av_attribute FOREIGN KEY (attribute_id) REFERENCES b2b_product_attributes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE b2b_products ADD CONSTRAINT fk_prod_category FOREIGN KEY (category_id) REFERENCES b2b_categories(id) ON DELETE SET NULL;
ALTER TABLE b2b_categories ADD CONSTRAINT fk_cat_parent FOREIGN KEY (parent_id) REFERENCES b2b_categories(id) ON DELETE SET NULL;
